sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t stephengrider/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true stephengrider/docker-react npm run test
  
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react-app-test"
  env: "DockerReactAppTest-env"
  bucket_name: "elasticbeanstalk-us-east-1-194921650603"
  bucket_path: "docker-react-app-test"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"

    
